[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "rpp_testing"
version = "0.1.0"
description = "Python implementation of RPP testing framework"
dependencies = ["setuptools"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["rpp_testing", "rpp_testing.*"]

[tool.setuptools.data-files]
"share/ament_index/resource_index/packages" = ["resource/rpp_testing"]
"share/rpp_testing" = ["package.xml"]
